### ISSUE TITLE
Understand and implement the transfer retry strategy

### ISSUE THREAD

**Issue by cinquo** [dmwm/AsyncStageout#2496]
This is what I have in the fts log file:
{{{
[SE][srmRm][SRM_AUTHENTICATION_FAILURE] httpg://gridse3.pg.infn.it:8443/srm/managerv2: SRM Authentication failed
lcg-del: Bad address
}}}

I understand that this kind of failures are going to let the jobs sitting on the agent till the issue is resolved. Potentially forever. Adding a retry-count/time limit is worth in this case.

**Comment by HassenRiahi** [comment]
First version of the retry has been implemented. Feedbacks for alogorithm evolution are dicussed here https://github.com/dmwm/AsyncStageout/issues/4321
