### ISSUE TITLE
Validation ASO/LifeCycle Agent setup  

### ISSUE THREAD

**Issue by HassenRiahi** [dmwm/AsyncStageout#4100]
As described here https://github.com/dmwm/AsyncStageout/issues/4080, please @dciangot could you have a look to the documentation and validate the new setup?

**Comment by HassenRiahi** [comment]
@dciangot , please could you point to the twiki for the integration instructions with the LifeCycle Agent?

**Comment by dciangot** [comment]
please close it.

@mmascher @belforte
