### ISSUE TITLE
Allow SE names instead of site names

### ISSUE THREAD

**Issue by bbockelm** [dmwm/AsyncStageout#4102]
If we are going to inject from the WN, we won't know the CMS site name for the temporary stageout location.  We only know the SE name (which is then translated to site name by the TaskWorker).

Can ASO change so it accepts a SE name (FQDN) as the source site (and do the PhEDEx datasvc lookup centrally)?

**Comment by mmascher** [comment]
This is not relevant anymore since we are taking the phedex-node from the WN now
