### ISSUE TITLE
Switch to Unix timestamps

### ISSUE THREAD

**Issue by bbockelm** [dmwm/AsyncStageout#4130]
We currently have a mixture of formatted time ('start_time': '2014-03-06 17:10:25.459102') and unix timestamps ('last_update': 1394122227) in the asynctransfer couch documents.

Is it possible to universally switch to timestamps?  One downside of human-readable time is that it does not appear to handle timezones correctly (think of what may happen when a job runs in the US and injects ASO document but ASO runs at CERN).

Thoughts?

**Comment by belforte** [comment]
obsolete (couchdb)
