### ISSUE TITLE
Kill correctly the users files transfers 

### ISSUE THREAD

**Issue by HassenRiahi** [dmwm/AsyncStageout#4196]
Currently the kill command is killing the file transfers in ASO but not in FTS. Since files belonging to various workflows can be in the same FTS job and FTS support only the kill per job and not per file, the current kill command in ASO is not implemented properly to kill effectively the transfers.

Talking to FTS dev., they do not have problems to include the support of files killing if it is a valid use-case. I will follow-up with Nicolo' to support the kill per files in FTS and then in ASO.

**Comment by juztas** [comment]
Seems killing individual files in FTS3 is not going further (7 months). If this will not gonna be implemented, we need a solution.

**Comment by HassenRiahi** [comment]
A directory per job retry or the append of a random string in the output as in CRAB2 has been already implemented in CRAB? I am following up to include the kill per file in the next release of FTS.

**Comment by HassenRiahi** [comment]
We need both in any case since it is known that the kill command could not actually kill the trnasfers.

**Comment by HassenRiahi** [comment]
The kill of single files is finally available in FTS.

**Comment by HassenRiahi** [comment]
It is tested and it seems working correctly in FTS. We need to implement the module that kills the FTS transfers in ASO.

**Comment by HassenRiahi** [comment]
The syntax is: DELETE /jobs/1234-5667-123/files/5689,5690,5695

**Comment by HassenRiahi** [comment]
I would split this ticket into:

* Include the FTS job id/file id in the ASO file doc. https://github.com/dmwm/AsyncStageout/issues/4276 
* View retrieving the FTS jobs ids/files ids of transfers to kill as well as the user details to retrieve his proxy. It could be an evolution of this view: https://github.com/dmwm/AsyncStageout/blob/master/src/couchapp/AsyncTransfer/views/forKill/map.js
* Tag the documents of transfers that will be killed in ASO. For instance set their status to KILLING instead of KILLED as it is acutally done here: https://github.com/dmwm/AsyncStageout/blob/master/src/couchapp/AsyncTransfer/updates/updateJobs.js  
* Implement a new module that start killing asynchronously the user's transfers once they are tagged for killing in ASO

How sounds?

**Comment by HassenRiahi** [comment]
@dciangot, you can find here a proposal for the implementation of an asynchronous KILL of single files.

Another approach is to KILL the transfers synchronously by the TW. So the TW will contact FTS to actually kill the files and then updates ASO db instead of only updating ASO DB as it is doing now (https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanKiller.py#L106). The implementation of this approach would require:

1. as above + FTS endpoint 
1. change forKill view to report back to TW the job id, file id and FTS endpoint
1. Include the FTS kill (HTTP DELETE) operation in the killTransfers method of the DagmanKiller in TW.
