### ISSUE TITLE
Report size and checksum to FTS3

### ISSUE THREAD

**Issue by bbockelm** [dmwm/AsyncStageout#4209]
Right now, we do not report the file size and checksum to FTS3; this means FTS3 is unable to estimate the amount of work remaining (and hence hurts our ability to document progress).

We should add this information as it is available in the CouchDB document.  For reference:

https://svnweb.cern.ch/trac/fts3/wiki/UserGuide#Submittingatransfer
https://svnweb.cern.ch/trac/fts3/wiki/FTSRest#PUTPOSTjobs

**Comment by juztas** [comment]
https://github.com/dmwm/AsyncStageout/pull/4468

**Comment by belforte** [comment]
I am afraid we need to understand where we are on this and finalize
