### ISSUE TITLE
Get rid of DBSPublisher.cache_area parameter

### ISSUE THREAD

**Issue by mmascher** [dmwm/AsyncStageout#4210]
Currently we have a parameter in the ASO:
```
config.DBSPublisher.cache_area = 'https://cmsweb-testbed.cern.ch/crabserver/preprod/filemetadata'
```
which is also used to determine the hash for myproxy (maybe that's the only case where it's used, I did not grep for it): https://github.com/dmwm/AsyncStageout/blob/3e60270316c36c34f256d3d89f9025280f4d331c/src/python/AsyncStageOut/PublisherWorker.py#L105

That should be taken from the couch document: ASO should not be bound to a single REST interface. Right now we cannot send tasks to the prod crab server REST and get them processed by an ASO which is also processing the requests coming from preprod.

PS A similar parameter exists for the TransferWorker.

**Comment by HassenRiahi** [comment]
For the implementation, see details here https://github.com/dmwm/AsyncStageout/issues/4348

**Comment by HassenRiahi** [comment]
Fixed.
