### ISSUE TITLE
Logging issue, not writing to ComponentLog

### ISSUE THREAD

**Issue by juztas** [dmwm/AsyncStageout#4236]
Log messages are written to stderr but not to ComponentLog. Looking more to see why it is not writing to ComponentLog, but writing to stderr.

**Comment by HassenRiahi** [comment]
https://github.com/dmwm/AsyncStageout/issues/4237 improves also the logging

**Comment by HassenRiahi** [comment]
Fixed here https://github.com/dmwm/AsyncStageout/pull/4445
