### ISSUE TITLE
HG1409 issue list to solve

### ISSUE THREAD

**Issue by juztas** [dmwm/AsyncStageout#4269]
First place :
1  Use service certificate for operations instead of Ops proxy #4256 & Don't fallback to ops proxy #4208
3  Change all queries which are in crontab and in all places to use stale=update_after. Also follow up on this if developer is not specifying anything, use always or ok or update_after. @geneguvo will comment here https://github.com/dmwm/WMCore/issues/5226

Less urgent
1  Use the opsProxy given in the config instead of the env. variable X509_USER_PROXY to contact couchDB #4060 
 Get wmc-dist-patch functional #4049 
3   Update the validation document of ASO database to check the transfer requests #4074 

In comming months
 Make the offsite variant in the deployment script compatible to the deployment script style used centrally #3981  (Not so critical so we (@juztas @geneguvo ) can do it together)

**Comment by HassenRiahi** [comment]
The tickets that have priority have been addressed and the other ones we have separate tickets for them. Closing this ticket.
