### ISSUE TITLE
Long-term monitoring for data-mining

### ISSUE THREAD

**Issue by TonyWildish** [dmwm/AsyncStageout#4283]
It would be very useful to have some long-term monitoring of the use and performance of ASO.

For example, if we can store the name, size, owner, CRAB-task, source and destination, creation and arrival time, for every file processed by ASO over a period of (say) 6 months, that would allow us to really see how it works and is used.

In particular, it would allow an analysis of per-user and per-task properties, which could lead to predictions on how to run jobs better. E.g. user X always generates a lot of data per job, so run their jobs at sites with good connectivity to the final destination.

Ideally we just need to pump the information into an oracle database (e.g. DMWMMON) to start with, we can see about compacting, archiving, deleting old stuff later on. The important thing to start with is not to lose too much data while setting this up.

Cheers,
Tony.

**Comment by belforte** [comment]
obsolete
