### ISSUE TITLE
Scalability issues, discussion, thoughts...

### ISSUE THREAD

**Issue by juztas** [dmwm/AsyncStageout#4284]
Several things which could be discussed or reviewed. Currently job uploads this document to couch database, but not all fields are required, because they are always static for specific workflow:

```
{
   "_id": "00001daa551b2e79653c88cc0e111c97554532209f89417f0ad343bf",
   "_rev": "3-f33c2d7496133d0fde181961e22ca369",
   "lfn": "/store/user/santocch.68589efd54e6b2f504806adbb10bd291f89ff9c4/10_aCrab_DoublePhoton_Crereco/DoublePhoton/crab_10_aCrab_DoublePhoton_Crereco/140915_104338/0002/mySearchTreeFile_2811.root",
   "checksums": {   # Is this used anywhere ?
       "adler32": "0", # This also
       "cksum": "0"   # This also .... 
   },
   "jobid": 2811,
   "size": 0,   # Is this used and or required for ASO, now it`s zero
   "group": "", # Look for [1]
   "destination": "T2_IT_Pisa", # Look for [1]
   "publish": 0, # Look for [1]
   "last_update": 1410936518,
   "source": "T2_US_Nebraska",
   "state": "done",
   "role": "", # Look for [1]
   "type": "output",
   "dbSource_url": "gWMS", # Now it`s static and always same... # Look for [1]
   "inputdataset": "/DoublePhoton/Run2012C-22Jan2013-v2/AOD", # Look for [1]
   "workflow": "140915_104338_crab3test-4:santocch_crab_10_aCrab_DoublePhoton_Crereco",
   "job_retry_count": 0,
   "start_time": "2014-09-17 01:45:58.921053",
   "job_end_time": "2014-09-17 01:45:58",
   "dbs_url": "https://cmsweb.cern.ch/dbs/prod/global/DBSReader", # Look for [1]
   "publication_retry_count": [
   ],
   "user": "santocch", # Look for [1]
   "publication_state": "not_published",
   "failure_reason": [
   ],
   "retry_count": [
   ],
   "end_time": "2014-09-17 08:48:38.391177",
   "publish_dbs_url": "https://cmsweb.cern.ch/dbs/prod/phys03/DBSWriter" # Look for [1]
}
```

[1]
If Crabserver would have new API call which gives all information where [1], it would lower each couch document size by 8 rows.
ASO knows from document workflow name and all these fields could be retrieved from Crabserver and ASO could cache these results (Not making request per each file, this data is static per workflow.)

[2](If we stay with couch)
There are 33 views in asynctransfer database. Reading several articles about performance and discussed with @geneguvo it could be usefull to rewrite `Map` and `Reduce` functions to `Erlang`. Not sure how much gain we would gain, but would be nice to see if its really gives a better performance 

[3]
From last fix we have a fix, that you can use any ASO, lets assume we set up one in Italy and or for debug purposes, or for rotating database we need to tell ASO where to look for filemetadata. This is needed for publication, because currently ASO has configuration where it sets where to look for filemetadata and it is pointing to one url. 

@geneguvo @HassenRiahi @mmascher @ericvaandering

**Comment by dciangot** [comment]
please close it.

@mmascher @belforte
