### ISSUE TITLE
make sure to import all fixes for DBS3 publication made in Crab2

### ISSUE THREAD

**Issue by belforte** [dmwm/AsyncStageout#4288]
given 
https://hypernews.cern.ch/HyperNews/CMS/get/wmDevelopment/640/2/1/1/1/1.html
I recommend a systematic comparison.

Or at least check that fixes done in Crab2 after initial implementation when code was cloned from Brian's first code are also present in Crab3 publication.
Here's a few useful pointers:
https://github.com/dmwm/CRAB2/issues?q=parent+in%3Atitle
https://github.com/dmwm/CRAB2/issues?q=publication+in%3Atitle
https://github.com/dmwm/CRAB2/issues?q=DBS3+in%3Atitle

**Comment by HassenRiahi** [comment]
Fixed here https://github.com/dmwm/AsyncStageout/pull/4377
