### ISSUE TITLE
Job failed with reason ended-finished 

### ISSUE THREAD

**Issue by HassenRiahi** [dmwm/AsyncStageout#4311]
Hi @TonyWildish,

It seems that the race condition in which the job is set as "failed" and the failure reason is "job ended-finished" is appearing again in ASO pre3. The only changes in the monitor compared to the other versions are:

https://github.com/dmwm/AsyncStageout/commit/a2c805661ef9d0954dd512d81ea82cc36f252950
https://github.com/dmwm/AsyncStageout/commit/740348ebab33e4cc89043afb45cbb1a14a404125

Any hints?

cheers
Hassen

**Comment by dciangot** [comment]
Hi @TonyWildish , 

I tried this fix, but again I get 100% job failed with failure reason "job-ended Finished". There should be something wrong in destination/source definition.

Diego
