### ISSUE TITLE
Validate  ASO 103pre5

### ISSUE THREAD

**Issue by dciangot** [dmwm/AsyncStageout#4345]
Please find the new RPM for ASO 103pre5 here: http://cmsrep.cern.ch/cmssw/comp.pre.riahi/RPMS/slc6_amd64_gcc481/

Release note in: https://github.com/dmwm/AsyncStageout/releases/tag/1.0.3pre5

ASO twiki as usual is: https://svnweb.cern.ch/trac/CMSDMWM/wiki/AsyncStageOutManagement

and please note that there is already a patch available: https://github.com/dmwm/AsyncStageout/pull/4344

**Comment by juztas** [comment]
So 2 issues :
1) 
```
2015-01-14 06:52:17: ASOMon[20300]: Reading config file /data/srv/asyncstageout/v1.0.3pre5/config/asyncstageout/monitor.conf
2015-01-14 06:52:17: ASOMon[20300]: Using FTS service https://fts3-pilot.cern.ch:8443/
Use of uninitialized value $me in concatenation (.) or string at /data/srv/asyncstageout/v1.0.3pre5/sw.pre.riahi/slc6_amd64_gcc481/cms/asyncstageout/1.0.3pre5/Monitor/perl_lib/ASO/Monitor.pm line 143.
: fatal error: cannot write to PID file (/data/srv/asyncstageout/v1.0.3pre5/install/asyncstageout/Monitor/aso-monitor.pid): No such file or directory
``` 
I used correct HG tag and as always followed tutorial. Fixed : `mkdir -p /data/srv/asyncstageout/v1.0.3pre5/install/asyncstageout/Monitor/work`

2)
It is not ASO bug, but FTS that it is reporting transfer successful but not able to retrieve file size :
https://fts104.cern.ch:8449///var/log/fts3//2015-01-14/srm.rcac.purdue.edu__srm-eoscms.cern.ch/2015-01-14-0727__srm.rcac.purdue.edu__srm-eoscms.cern.ch__303890559__da4b6256-9bbd-11e4-b211-02163e00a17a
```
Wed Jan 14 08:27:30 2015 DEBUG    SRM context invalidated for httpg://srm-eoscms.cern.ch:8443/srm/v2/server
Wed Jan 14 08:27:30 2015 DEBUG       [gfal_srm_statG] try to stat file srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms/store/user/jbalcas/MinBias/publish_name/150114_070255/0000/log/cmsRun_408.log.tar.gz
Wed Jan 14 08:27:30 2015 DEBUG       [gfal_srm_statG] store srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms/store/user/jbalcas/MinBias/publish_name/150114_070255/0000/log/cmsRun_408.log.tar.gz stat info in cache
Wed Jan 14 08:27:30 2015 ERROR    DESTINATION file size is 0
Wed Jan 14 08:27:30 2015 INFO     Report FAILED back to the server
```
```
[jbalcas@lxplus0131 ~]$ eos ls -l eos/cms/store/user/jbalcas/MinBias/publish_name/150114_070255/0000/log/cmsRun_408.log.tar.gz
-rw-r--r--   2 jbalcas  zh               3951 Jan 14 08:27 cmsRun_408.log.tar.gz
```

So until now all good and works, will test more today ;)

**Comment by HassenRiahi** [comment]
I will report the issue to FTS devel. but it seems that it is not happenning to all files transferred to EOS@CERN. From the example that you sent only 1 file from 10 has failed for that error and all others have been transferred correctly.

**Comment by HassenRiahi** [comment]
For FTS devel., it seems to be an EOS bug because the SRM response from EOS here https://fts104.cern.ch:8449///var/log/fts3//2015-01-14/srm.rcac.purdue.edu__srm-eoscms.cern.ch/2015-01-14-0727__srm.rcac.purdue.edu__srm-eoscms.cern.ch__303890559__da4b6256-9bbd-11e4-b211-02163e00a17a.debug is reporting:

<size xsi:type="xsd:unsignedLong">0</size>

So EOS is indeed reporting a file size of 0.

Please report this issue to EOS team.

**Comment by HassenRiahi** [comment]
Done and deployed in prod. Closing the ticket.
