### ISSUE TITLE
Use 'rest_host' and 'rest_uri' from couch docs

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/AsyncStageout#4348]
These two parameters contain respectively the REST host machine (e.g. 'cmsweb.cern.ch', or in case I use my private installation it will be 'vmatanasi2.cern.ch') and the REST URI without the API (e.g. '/crabserver/prod', or in case of a private installation it will be '/crabserver/dev'). These parameters should be used to build the REST URL (ASO should add the corresponding API).
One use case is the output files metadata.
ASO should use this REST URL to get the output files metadata. Currently, if I use my private CRABServer and I upload the output files metadata to my private database, publication will fail because ASO tries to get the output files metadata from the production database.

**Comment by HassenRiahi** [comment]
Fixed.
