### ISSUE TITLE
Validate of ASO 103pre6

### ISSUE THREAD

**Issue by HassenRiahi** [dmwm/AsyncStageout#4363]
The release notes could be found here https://github.com/dmwm/AsyncStageout/releases/tag/1.0.3pre6 and the documentation has been updated https://svnweb.cern.ch/trac/CMSDMWM/wiki/AsyncStageOutManagement

**Comment by juztas** [comment]
@HassenRiahi please close it

**Comment by HassenRiahi** [comment]
Bug is found here https://github.com/dmwm/AsyncStageout/issues/4376

**Comment by HassenRiahi** [comment]
Bug in the pre has been reported here https://github.com/dmwm/AsyncStageout/issues/4376. Closing this ticket.
