### ISSUE TITLE
Clean old documents in couch prod

### ISSUE THREAD

**Issue by juztas** [dmwm/AsyncStageout#4364]
https://cmsweb.cern.ch/couchdb/_utils/database.html?asynctransfer/_design/AsyncTransfer/_view/JobsByFailuresReasons
end_time has changed to job_end_time. 

@HassenRiahi when we will have new views ? if not soon you can assign this to me

**Comment by HassenRiahi** [comment]
Maybe the opposite. The docs that you are pointing out are dated from 08/2014 and they have never been cleaned from there. So by changing that param. (maybe happened in Sept. ) the new release was not able to remove them when rotating the DB. Maybe it is the case to remove them by hand from the DB.

**Comment by AndresTanasijczuk** [comment]
From the CRAB server point of view, end_time and job_end_time exist since long long time in the ASO couch documents, and their values definition have not changed in cmscp or PostJob.

**Comment by juztas** [comment]
I was thinking about going with clean database whenever we will have final views which I heard you already done and had really great performance ;)

**Comment by HassenRiahi** [comment]
Yes. Diego is validating the views in pre6 in devel. instance. Once he will give us the green light we can request the testbed deployment. @dciangot could we proceed with the testbed deployment?

**Comment by dciangot** [comment]
Yes, I tested it with the injection of 1 file. So I think you can procede with the deployment.

**Comment by juztas** [comment]
February release requests was closed on 18 of January. @HassenRiahi or @dciangot can you create request to cmsdist? We will have more time to test until March deployment.

**Comment by HassenRiahi** [comment]
Let's then wait Diego to open the requests for March to upgrade couch. Between we have the pre6 that we need to validate https://github.com/dmwm/AsyncStageout/issues/4363.

**Comment by dciangot** [comment]
please close it.

@mmascher @belforte
