### ISSUE TITLE
Using multiple FTS server

### ISSUE THREAD

**Issue by merictaze** [dmwm/AsyncStageout#4371]
Instead of having one FTS server in the config, and let all the transfers use it, it may be better to 
- allow multiple FTS server usage, or
- add fallback mechanism to try with a different FTS server if the current one is continuously failing.

This can solve the issue with failing ASO transfers due to down/non-functioning FTS server.

Regards,
Meric

**Comment by HassenRiahi** [comment]
allow multiple FTS server usage, or

1 instance should be enough for all CMS transfers so I do not think that we need more than 1 instance only for ASO service

    add fallback mechanism to try with a different FTS server if the current one is continuously failing.

+1.

**Comment by HassenRiahi** [comment]
The implementation requires the following:
- the submitter can support a list of FTS server. It fallbacks to the next in the list if the first one does not reply.  
- The same thing is needed in the monitor component. It should be able to accept a list of FTS servers and it will retrieves the status from the next in the FTS server list if the first one does not reply. 

I am opening 2 tickets to include this feature.

**Comment by belforte** [comment]
@dciangot can you say if this was done, or does still make sense ? I suspect we are happy with one server in the config.

**Comment by dciangot** [comment]
It will require a huge effort to implement it and I don't know if it is worth. In case of FTS problem we can stop the aso instance and turn on another one with a different fts server. If the broken fts stays down for more than 6h, all the jobs submitted will be retried and eventually processed by the other instance.

**Comment by belforte** [comment]
So, we do no need it until we hit a blocker. Closing
