### ISSUE TITLE
Report ASO metrics to Kibana

### ISSUE THREAD

**Issue by juztas** [dmwm/AsyncStageout#4373]
Report information to Kibana:
1) Service status (AsyncStageout, DBSPublisher, FilesCleaner, Monitor)
2) Num of files in status (new, acquired, failed, transferred)
3) publication status
what else?

**Comment by TonyWildish** [comment]
monitor queue length?

**Comment by hernand** [comment]
it would be good to monitor the postjob latency (time between a transfer is done in ASO and the postjob marking the job as done). As you know, once the processing part of the job is done, the postjob is started by dagman and polls ASO checking the transfer status of the output files. The number of postjobs running in parallel for a given task is limited to avoid having too many postjobs running in the schedd (each postjobs takes few MB of RAM). This can introduce some significant latency between the output files becoming available and crab marking the job as completed. This postjob latency can be a good indicator of ASO long transfer latencies. Almost a year ago, with the help of Hassen and the dashboard people, I studied the postjob latency . IIRC we took the transfer completion timestamp from the ASO DB and the job done timestamp from the dashboard. We needed to correlated job by job which was OK for our exercise but not for this monitoring. So, not sure if one can get from the ASO DB the necessary information to monitor the postjob latency distribution

**Comment by TonyWildish** [comment]
I don't see the value of measuring postjob latency as a proxy for long transfer times. ASO can measure the transfer times directly, in the Monitor component. Why not use that? Or have I missed the point?

**Comment by HassenRiahi** [comment]
> So, not sure if one can get from the ASO DB the necessary information to monitor the postjob latency distribution

From ASO, we can propgating to kibana the number of files in status completed/failed in ASO by time bin (minutely, hourly,...) as well as the task name. Then the Dashboard should provide the distribution of the completed job over time for a given task (so far it seems that only distrbution of the completed jobs over sites for a given task is provided). The 2 plots together could provide us an estimation of this latency.

**Comment by TonyWildish** [comment]
so what exactly are we trying to measure? The postjob-latency, ASO latency, or ASO (==FTS) transfer times? Maybe it's just me but it seems we're confusing them?

**Comment by AndresTanasijczuk** [comment]
Jose proposes to measure the post-job latency, which from a users' point of view is part of the transfer time.
Keep in mind that the post-job waits until ALL transfers in a job are in a terminal state. So the post-job latency strictly speaking is something that should be measured per job, not per file (or be measured only in tasks that have 1 file to transfer per job).

**Comment by hernand** [comment]
Tony, sorry for the confusion. My proposal was to monitor the (artificial) transfer latency (as perceived by the users) added by the postjobs. This is not really an ASO metrics but a CRAB3 one.  But it looks it cannot be easily measured/monitored.

**Comment by dciangot** [comment]
Everything in place. Included the ASO latency measure available soon on crab monitor ui for transfer managed by ASO/Oracle instance (the pj additional latency would be at max: ASO latency+30min).
IMO we can close and reopen just in case of further issues.

@mmascher @belforte
