### ISSUE TITLE
Expose ASO config. param

### ISSUE THREAD

**Issue by HassenRiahi** [dmwm/AsyncStageout#4374]
As discussed here https://github.com/dmwm/AsyncStageout/issues/4321, the number of retry and cool-off period should be exposed. Now they are in the config. database of the local couch. It is the case to move the config. database of ASO to the central couch in cmsweb so that CRAB3/postjob could know about it.

**Comment by dciangot** [comment]
The number of retry will come with oracle pretty staight. Regarding cool-off the value is fixed by crab design (eg. keep all the retries inside 24h of the postjob timeout), so I don't feel the need to expose it.
