### ISSUE TITLE
Monitor in 1.0.3pre6 doesn't write 'failure_reason' in the Reporter-*.json files.

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/AsyncStageout#4376]
I installed ASO 1.0.3pre6 and I had the problem that the ReporterWorker was failing in https://github.com/dmwm/AsyncStageout/blob/master/src/python/AsyncStageOut/ReporterWorker.py#L170 because the json file doesn't have 'failure_reason'.

**Comment by HassenRiahi** [comment]
Fixed in the new releases.
