### ISSUE TITLE
Review documentation in CMSDMWM AsyncStageOutManagement

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/AsyncStageout#4378]
This page https://svnweb.cern.ch/trac/CMSDMWM/wiki/AsyncStageOutManagement needs some updates. 
1) The cron jobs can all use --cert /data/srv/asyncstageout/state/asyncstageout/creds/OpsProxy --key /data/srv/asyncstageout/state/asyncstageout/creds/OpsProxy (no need to use --cert /data/ASO/certs/proxy.cert --key /data/ASO/certs/proxy.cert).
2) Is the cron "57 */4 * * * /data/proxy/vomsrenew.sh &> /tmp/vomsrenew.log" (and therefore the script vomsrenew.sh) needed?
3) In section "ASO test instance", is the auth_aso_plugin.config file still supported?
4) Section "Config" I think is not needed anymore, because the Couch URL is now read from the $ASYNC_SECRETS_LOCATION file and correctly set in the config.
5) Under "Hardware requirements" I suggest to add some information there. I installed ASO in a CERN OpenStack VM that I requested with these specifications (m1.medium, 4GB RAM, 2 VCPU, 40.0GB Disk) and after a few days of light usage I ran into the problem that I had no more space on disk because the directory $INSTALL_COUCH/database/ was full.
6) The Note in section Initialising AsyncStageOut is not needed (unless you want to keep it for older versions of ASO?). It says:
"Fix the couchURLs in the ASO config file to your CouchURL instance." but the URLs are already ok.
"Comment the Analytics component section." but there is no Analytics component anymore.
7) All in all, in this page needed? Can it not be merged with https://twiki.cern.ch/twiki/bin/view/CMSPublic/AsoDeployment ?

**Comment by HassenRiahi** [comment]
Thank you @AndresTanasijczuk for reviewing the documentation. Please find comments inline:

> 1) The cron jobs can all use --cert /data/srv/asyncstageout/state/asyncstageout/creds/OpsProxy --key /data/srv/asyncstageout/state/asyncstageout/creds/OpsProxy (no need to use --cert /data/ASO/certs/proxy.cert --key /data/ASO/certs/proxy.cert).

Yes

> 2) Is the cron "57 */4 * * * /data/proxy/vomsrenew.sh &> /tmp/vomsrenew.log" (and therefore the script vomsrenew.sh) needed?

No

> 3) In section "ASO test instance", is the auth_aso_plugin.config file still supported?

Yes

> 4) Section "Config" I think is not needed anymore, because the Couch URL is now read from the $ASYNC_SECRETS_LOCATION file and correctly set in the config.

Yes

> 5) Under "Hardware requirements" I suggest to add some information there. I installed ASO in a CERN OpenStack VM that I requested with these specifications (m1.medium, 4GB RAM, 2 VCPU, 40.0GB Disk) and after a few days of light usage I ran into the problem that I had no more space on disk because the directory $INSTALL_COUCH/database/ was full.

It is strange that you get 40 GB of disk full after a few days. Are you compacting the DB/views by installing correctly the cron jobs? do you know what is consuming the disk: database or cache? consider that in prod there are nearly 2 millions of docs and the dabase size is nearly 7 GB. But of course if you are doing scale tests you can end up by filling the disk even in 1 hour. I would say m1.medium, 4GB RAM, 2 VCPU, 40.0GB Disk is enough for testing purposes.       

> 6) The Note in section Initialising AsyncStageOut is not needed (unless you want to keep it for older versions of ASO?). It says:
"Fix the couchURLs in the ASO config file to your CouchURL instance." but the URLs are already ok.
"Comment the Analytics component section." but there is no Analytics component anymore.
 
Please remove it 

> 7) All in all, in this page needed? Can it not be merged with https://twiki.cern.ch/twiki/bin/view/CMSPublic/AsoDeployment ?

Please remove all pointers from https://twiki.cern.ch/twiki/bin/view/CMSPublic/AsoDeployment and update it with the missed info.

**Comment by AndresTanasijczuk** [comment]
I have copied all the relevant info from https://svnweb.cern.ch/trac/CMSDMWM/wiki/AsyncStageOutManagement to https://twiki.cern.ch/twiki/bin/view/CMSPublic/AsoDeployment and removed from the latest the pointers to the first. So I am closing this issue.

**Comment by belforte** [comment]
thanks !
