### ISSUE TITLE
Investigate why only the last transfer retry is showhn in dashboard

### ISSUE THREAD

**Issue by mmascher** [dmwm/AsyncStageout#4379]
see for example job22 of http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=default&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=150216_153758_crab3test-2%3Apiedra_crab_QCD_Pt-20toInf_PU20bx25_PHYS14_skim which only shows one transfer and not all the transfer retries: http://dashb-cms-job.cern.ch/dashboard/request.py/ftsfilestatus?jobId=947482324

**Comment by HassenRiahi** [comment]
Now all the transfer retries within a job version are shown correctly in the dashboard http://dashb-cms-job.cern.ch/dashboard/request.py/ftsfilestatus?jobId=989231360
