### ISSUE TITLE
Prepare twiki for operators to answer question "Why my transfers are so slow?"

### ISSUE THREAD

**Issue by mmascher** [dmwm/AsyncStageout#4380]
Discussing with Hassen we realized that our beloved operators (both CRAB3 and transfer team operators :)) might profit from some instructions to help answer this question. Hassen says that there are already plots that shows bad links and things like that, and he agreed to prepare a twiki that show step by step how to recognize that transfer are stuck (both in general and for a specific workflow), so that we can show this to the users.

**Comment by HassenRiahi** [comment]
@juztas will take care to update the ASO operations documentation.

**Comment by belforte** [comment]
we do not really have any ready recipe for twiki
