### ISSUE TITLE
Validate of ASO 103pre8

### ISSUE THREAD

**Issue by HassenRiahi** [dmwm/AsyncStageout#4398]
The release notes can be found here https://github.com/dmwm/AsyncStageout/releases/tag/1.0.3pre8

**Comment by HassenRiahi** [comment]
@juztas news? do you have a timescale to get this validated?

**Comment by juztas** [comment]
Monitor still has this problem with creating directory Monitor/work/ directory. 
Full validation cycle will start together with CMSWeb validation, which should be deployed tomorrow.

**Comment by HassenRiahi** [comment]
pls could you fix 1) since @dciangot is not able to reproduce the issue. For 2) ok for me even if this ASO release is not tight to CMSWEB deployment cycle. But I understand that you want to validate everything together.

**Comment by HassenRiahi** [comment]
Done.
