### ISSUE TITLE
Revisit PublisherWorker migrateByBlockDBS3

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/AsyncStageout#4402]
These lines https://github.com/dmwm/AsyncStageout/blob/1.0.3pre8/src/python/AsyncStageOut/PublisherWorker.py#L650-651 I think will not work if there is no input dataset, as in the case of running CRAB over input files published in DBS but a la user input files. Actually, not sure if publication is expected to work at all in this case.

**Comment by belforte** [comment]
will deal with this when (if ever) we support publication for jobs w/o a DBS input
