### ISSUE TITLE
Implement a tool to facilitate users’ cleaning of a remote SE area using FTS bulk deletion

### ISSUE THREAD

**Issue by HassenRiahi** [dmwm/AsyncStageout#4408]
When a user asks for cleaning their outputs in the remote SE, there are various scenario:

1- The user outputs are still in ASO database (the metadata are removed from ASO DB after 1 month)
2- The user outputs are registred in the local DBS (the default value of the publication flag is on)
3- The user outputs were removed from ASO DB and were not published in the local DBS

I would say that we need to cover point 1 and 2 at least initially since 3 includes outputs that become out of CMS catalogues and so users would be asked in this case to straight use the generic Grid tools (FTS/GFAL) to remove their outputs. 

How sounds?

@TonyWildish @hernand

**Comment by hernand** [comment]
who requested this? I don't remember any more. Does everyone agree on having such a tool?
In any case, I would limit the tool to deal with case 2. I don't think we should only rely on static data. I think the input should be the dataset name and then the tool should delete the files and unregister/invalidate the dataset in DBS. The same thing PhEDEx deletion requests do for production data.
A deletion tool, specially a bulk one,  is a delicate thing... One should be 100% sure that a user can only delete his/her data. I guess the cert proxy should guarantee that.

**Comment by HassenRiahi** [comment]
It is an income from the user data review for ASO https://docs.google.com/document/d/17YquAHNXF6hnJjqZHw8O3u1q9Y37kuf2pwCfp_roASA
###########
Develop a tool to facilitate users’ cleaning of a remote SE area, leveraging on bulk removal capability now available in FTS3. Since ASO already has an interface to FTS3 and capability to work with users’ proxies.
#######

**Comment by hernand** [comment]
ah, I see. I had forgotten. Maybe more people should be involved in the discussion, to make sure this is a useful thing to have and help define the use cases. Maybe a post to the crab-dev HN? In my view, one should start with use case 2.

**Comment by HassenRiahi** [comment]
Just discussed in crab dev meeting. It seems that the recursive removal of directory is now supported in gfal. So no devel. efforts is needed here at least for now. Only the documentation will be improved to point out users to the gfal-rm syntax.

**Comment by HassenRiahi** [comment]
Agreed to document the recursive gfal-rm command and point it out to users.
