### ISSUE TITLE
if source&dest site is the same it deletes files from /store/group

### ISSUE THREAD

**Issue by juztas** [dmwm/AsyncStageout#4429]
Please see corresponding issue:
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/879.html
and here is the problem: https://github.com/dmwm/AsyncStageout/blob/master/src/couchapp/AsyncTransfer/views/LFNSiteByLastUpdate/map.js

Currently ASO is patched on production not to delete anything from store/group.

@HassenRiahi can you set highest prio and would be good to have it in this release.

**Comment by belforte** [comment]
was this happening because we are still using /store/temp/group ?
so we may need to revisit when fixing and make sure there is consistency
https://github.com/dmwm/CRABServer/issues/4907
(maybe all is OK, I add this comment only as a reminder to verify)

**Comment by juztas** [comment]
I think double checks will not break anything, but good to have ;)
