### ISSUE TITLE
DB Rotation is taking too long 

### ISSUE THREAD

**Issue by HassenRiahi** [dmwm/AsyncStageout#4437]
The rotation took too long to rebuild the AsyncTransfer couchapp. Before it was taking too long to rebuild the Monitor couchapp and it seems splitting the views into various couchapp has improved the situation. Now we need to split the AsyncTransfer couchapp into various ones. 

Alternatively, @juztas is discussing the views implementation in Erlang (initial pull request is here  https://github.com/dmwm/AsyncStageout/pull/4303).

**Comment by mmascher** [comment]
Hi, what about starting a new database from scratch when we need to perform a DB rotation?

**Comment by HassenRiahi** [comment]
I think we can use ASO@preprod during the operation by pointing in the CRABServer prod config. to the ASO url @preprod. Then everything is expected to work out of the box (I guess). Maybe we can give it a try:  
1) we have another instance of couch@dev (in addition to couch@preprod) 
2) we need to setup an ASO attached to couch@dev. 
3) start submitting to prerod then at some some we switch the CRABServer preprod config. to point to ASO@dev.

**Comment by mmascher** [comment]
Yes, even something along those lines. I wanted to ask Diego if it is possible to set up a new database and a new redirection on cmsweb (we use cmsweb.cern.ch/couch2/asynctransfer in the REST that through a apache redirection points to cmsweb.cern.ch/couch/asynctransfer2). But also using cmsweb-testbed during the intervention would work.

The drawback is that monitor systems based on couch would not work. But AFAIK this is something we can sacrifice.

**Comment by dciangot** [comment]
After one year battle it looks solved with the current design. Please close it.

@belforte @mmascher
