### ISSUE TITLE
workflow_duration can have negative values

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/AsyncStageout#4442]
workflow_duration defined in https://github.com/dmwm/AsyncStageout/blob/1.0.3pre14/src/python/AsyncStageOut/PublisherWorker.py#L237 can have negative values.
On one hand we define the 'end_time' in the couch docs as str(datetime.datetime.now()); then the 'publish' view emits doc.end_time.split('.')[0] and then we finally do https://github.com/dmwm/AsyncStageout/blob/1.0.3pre14/src/python/AsyncStageOut/PublisherWorker.py#L200-L202.
On the other hand we define now = time.time() in https://github.com/dmwm/AsyncStageout/blob/1.0.3pre14/src/python/AsyncStageOut/PublisherWorker.py#L170.

**Comment by belforte** [comment]
let's hope this was CouchDB related, if it surfaces in the Oracle instance we'll deal with ti then
