### ISSUE TITLE
Set transfer priority in FTS3, coordinate with PhEDEx

### ISSUE THREAD

**Issue by HassenRiahi** [dmwm/AsyncStageout#4444]
Requested by @PerilousApricot here https://github.com/dmwm/AsyncStageout/issues/4436

> I guess an added optimization would be to set the FTS priority for ASO transfers to be the same as the FTS priority for "Normal" PhEDEx subscriptions. We (Vanderbilt) are stuck with a 10Gig link for A possibly another ~18 months because of beaurocracy and we're pegging the link more and more often with a combination of PhEDEx/ASO/xrootd. Since most PhEDEx replications are low priority and CRAB3/ASO cares more about latency, having FTS3 prioritize ASO over PhEDEx would help keep ASO timeouts down.

@nikmagini how sounds?

**Comment by HassenRiahi** [comment]
FTS3 supports actually only the setting of the activity share per VO and not per endpoint.

**Comment by nikmagini** [comment]
Hi Hassen,

given the usecase mentioned in https://github.com/dmwm/AsyncStageout/issues/4436 I don't think that we need to set an activity share per endpoint. A global VO activity share for ASO looks sufficient. Why don't you try it and see what happens? Looking at the recent Dashboard history, a share of 40% looks OK for ASO:

http://dashb-fts-transfers.cern.ch/ui/plot.html#date.interval=40320&l.grouping=activity&p.grouping=activity&p.stat=successes&r.grouping=activity&server=%28bnl,cmsfts3.fnal.gov,fts.hep.pnnl.gov,fts3-pilot.cern.ch,fts3.cern.ch,lcgfts3.gridpp.rl.ac.uk%29&tab=transfer_plots&vo=%28cms%29

**Comment by PerilousApricot** [comment]
I'm not exactly sure why we're talking about setting an activity share...I
don't even think it will do what I was looking to solve.

The PhEDEx FTS backend calls glite-transfer-set-priority for each job, and
tells FTS how important a transfer is. My suggestion was to have ASO do the
same thing.


-- 
Sent from Gmail Mobile

**Comment by PerilousApricot** [comment]
See:

https://github.com/dmwm/PHEDEX/blob/master/perl_lib/PHEDEX/Transfer/Backend/Interface/GliteAsync.pm#L193

**Comment by belforte** [comment]
renamed issue
