### ISSUE TITLE
PublisherWorker crashes if primary daset mimics an input dataset

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/AsyncStageout#4455]
In the ASO Couch documents, the field `inputdataset` is whatever the CRAB server received in its `inputdata` REST parameter. And this `inputdata` REST parameter is used to pass real input dataset names, but also primary dataset names in PrivateMC tasks and Analysis tasks with user files. ASO assumes that in the second case `inputdataset` is not of the form "/A/B/C". And this was true until the October cmsweb deployment, when the CRAB server started to require users to give a primary dataset of the form "/A/B/C" for Analysis tasks with user files. This is causing the PublisherWorker to crash in https://github.com/dmwm/AsyncStageout/blob/1.0.3pre14/src/python/AsyncStageOut/PublisherWorker.py#L853 To avoid the PublisherWorker component keep crashing for users that already sent tasks with a primary input dataset name of the form "/A/B/C", we can add a check if "/A/B/C" is in the input DBS URL or not.

I know @belforte will not like that we make such kind of patches and would prefer that we tackle the issue from root. The fixing from root will be done by fixing the CRAB server to use a different parameter for primary datasets. I am already working on it. And at that point we can evaluate if we can just leave the Couch field `inputdataset` empty for tasks with no real input dataset, or if we also need to add a `primarydataset` field in the ASO Couch documents. That would be for me the best solution for ASO side. In the meantime, I talked with @mmascher and @HassenRiahi and we three agree that the patch mentioned above in ASO is important. I will open a separate issue for "Check if Couch inputdataset can be left empty for tasks with no real input dataset, or add a new parameter for primary dataset names".

**Comment by belforte** [comment]
I agree that this should be fixed.
My position is that we could take our time to fix things and simply rush in the
client a quick patch that disables "running on a bunch of files".

**Comment by belforte** [comment]
what really disturbs me here, is the idea to publish when input is "just a bunch of files".
This is basically the same as publishing a list of files from "the street" (quoting D.Riley).
We surely know how to insert them in DBS, but we must first make sure we have defined how to handle 
all metadata (or lack of them), then we rather do it in the general context.
I do not want to go there w/o full awareness, discovering one issue at a time when tasks fail or 
published data show problems later on.

I should have payed more attention when this was first introduced. In the end is something users 
could keep living w/o for a few months and we could have used this time to improve the fundamentals.

**Comment by belforte** [comment]
@belforte needs to review and decide what to do
