### ISSUE TITLE
About the inputdataset parameter in Couch documents

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/AsyncStageout#4456]
See https://github.com/dmwm/AsyncStageout/issues/4455

Q1: Does ASO uses primary input dataset names for something?

Q2: If A1 == yes, shouldn't we create a new field in Couch documents where to store the primary dataset names? Using a same parameter (`inputdataset`) for two different things (input datasets and primary datasets) has been proven to be a very bad idea (https://github.com/dmwm/AsyncStageout/issues/4455).

Q3: If A1 == no, can then the CRAB server leave the `inputdataset` parameter empty for tasks with no real input dataset?

**Comment by belforte** [comment]
obsolete (no couch anymore)
