### ISSUE TITLE
Remove ugly workaround when CRABServer issue 5031 is fixed.

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/AsyncStageout#4458]

**Comment by AndresTanasijczuk** [comment]
The ugly workaround is https://github.com/dmwm/AsyncStageout/pull/4457
CRAB Server issue https://github.com/dmwm/CRABServer/issues/5031

**Comment by AndresTanasijczuk** [comment]
https://github.com/dmwm/CRABServer/issues/5031 was fixed in November release.

**Comment by belforte** [comment]
let me try to start assigning ASO issues to Diego :-)

**Comment by belforte** [comment]
hmm... apparently @AndresTanasijczuk fixed this with https://github.com/dmwm/AsyncStageout/pull/4465 but GIT has not added any reference, maybe it needs for the PR to be merged. @dciangot ?
