### ISSUE TITLE
Error msg moved to WMCore

### ISSUE THREAD

**Issue by juztas** [dmwm/AsyncStageout#4472]
This place: https://github.com/dmwm/AsyncStageout/blob/master/src/python/AsyncStageOut/ReporterWorker.py#L354-L372
has to use https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMExceptions.py#L253-L291

CRAB3 is also moving to same. It is easier to maintain in one location all list https://github.com/dmwm/CRABServer/issues/5133

**Comment by dciangot** [comment]
I'm not sure if we want to be independent of that or not. Personally I would agree that the maintanance will benefit and I can try to test it in the next deployment

**Comment by belforte** [comment]
we should do this
