### ISSUE TITLE
All new delegations are failing

### ISSUE THREAD

**Issue by juztas** [dmwm/AsyncStageout#4475]
Due to this: https://github.com/dmwm/AsyncStageout/commit/525126389287f1e6b46dbad50652951bbc9bfd02

**Comment by juztas** [comment]
This now affects all new users and whom proxies are expired on ASO. @dciangot can you take care of it asap ?

**Comment by dciangot** [comment]
Fixed and restarted

**Comment by HassenRiahi** [comment]
Fixed.
