### ISSUE TITLE
The new prod. ASO instance @vocms021 is broken  

### ISSUE THREAD

**Issue by HassenRiahi** [dmwm/AsyncStageout#4478]
See details here: https://ggus.eu/?mode=ticket_info&ticket_id=119472

**Comment by HassenRiahi** [comment]
@nikmagini

**Comment by HassenRiahi** [comment]
https://its.cern.ch/jira/browse/FTS-486

**Comment by HassenRiahi** [comment]
Setting the owner/group of /etc/grid-security/host*.pem files to root has fixed the issue. I do not know what/who has recently changed the permissions on those files in vocms021.

**Comment by dciangot** [comment]
And moreover, we didn't (or barely did) notice that on the test, so for the future maybe is better to remember to submit test task after manually removing the proxy, of something like that.

**Comment by HassenRiahi** [comment]
It was noticed during the test because maybe you were also submitting to the other aso instance vosm031 and so you proxy gets delegated to FTS from that host. The issue when you want to delegate the proxy from the new host, vocms021, to FTS, it fails.

**Comment by dciangot** [comment]
Ok, so speaking just to avoid similar delegation issue unseen on the test, how should we proceed?

**Comment by HassenRiahi** [comment]
Eveything seem working soomthly now after changing back the permissions on host*.pem files. So we can include the instance back in prod. now.

**Comment by belforte** [comment]
This needs to be part of the ASO installation script.
As much as possible of the procedure should be made automatic, a long list of actions in a twiki is not safe.
At some point we need to review the ASO installation, make sure it is as much puppettized as possible etc.
This should sort of come naturally as we reinstall one server every one/two months as part of the new rotation procedure.

**Comment by belforte** [comment]
old. close. anyhow ASO installation must be on puppettized machines now, where host*pem files are automatically managed
