### ISSUE TITLE
Puppetize limit on number of open files

### ISSUE THREAD

**Issue by dciangot** [dmwm/AsyncStageout#4480]
From yesterday evening FTS monitor on vocms021 began to crash time to time (sometimes after 2h, then after 8h) with the following reason (*).
As a temp solution I have added a cron that cleanups finished jobs from work monitor folder and restart the component as soon as this happen. During the night all worked fine.

Still we need to investigate why it is happening.

(*)

```
2016-02-12 08:29:57: ASO-Monitor.pl[244908]: Component::Child::Run: WheelID is not defined
2016-02-12 08:29:57: ASO-Monitor.pl[244908]: {'FTSJOB' => bless( {'X509_USER_KEY' => '/data/srv/asyncstageout/state/asyncstageout/creds/ecd0a5b03fa21ef12077d8fbfa20e7cd667d23af','ID' => 'ab3813b8-d156-11e5-ab4a-02163e009e85','JOB_POSTBACK' => undef,'SUMMARY' => 'ETC=0 JOB_STATE=Submitted FILE_STATES: Submitted=1','VERBOSE' => 0,'TIMESTAMP' => 1455261008,'SPACETOKEN' => undef,'LOG' => ['1455260615 created... 
','glite-transfer-status -l  --verbose -s https://fts3.cern.ch:8443 ab3813b8-d156-11e5-ab4a-02163e009e85 
','Request ID:  ab3813b8-d156-11e5-ab4a-02163e009e85 
--
','  Reason:      
','  Duration:    0
'],'X509_USER_PROXY' => '/data/srv/asyncstageout/state/asyncstageout/creds/ecd0a5b03fa21ef12077d8fbfa20e7cd667d23af','STATE' => 'Submitted','TIMEOUT' => '72000','TEMP_DIR' => undef}, 'ASO::Job' ),'PID' => 0,'_priority' => '1.79769313486232e+308','ENV' => {'X509_USER_KEY' => '/data/srv/asyncstageout/state/asyncstageout/creds/ecd0a5b03fa21ef12077d8fbfa20e7cd667d23af','PHEDEX_FAKEFTS_RATE' => undef,'X509_USER_PROXY' => '/data/srv/asyncstageout/state/asyncstageout/creds/ecd0a5b03fa21ef12077d8fbfa20e7cd667d23af','X509_USER_CERT' => '/data/srv/asyncstageout/state/asyncstageout/creds/ecd0a5b03fa21ef12077d8fbfa20e7cd667d23af','PHEDEX_FAKEFTS_MAP' => undef},'LOGFILE' => '/dev/null','CMD' => ['glite-transfer-status -l  -s https://fts3.cern.ch:8443 ab3813b8-d156-11e5-ab4a-02163e009e85'],'_action' => bless( sub { "DUMMY" }, 'POE::Session::AnonEvent' ),'TIMEOUT' => 60,'KEEP_OUTPUT' => 1}
244908: !!! Child process PID:60148 reaped: 
244908: !!! Child process PID:60158 reaped: 
244908: !!! Child process PID:60188 reaped: 
244908: !!! Child process PID:60197 reaped: 
244908: !!! Child process PID:60229 reaped: 
244908: !!! Child process PID:60222 reaped: 
244908: !!! Child process PID:60207 reaped: 
244908: !!! Your program may not be using sig_child() to reap processes.
244908: !!! In extreme cases, your program can force a system reboot
244908: !!! if this resource leakage is not corrected.
couldn't fork: Resource temporarily unavailable at /data/srv/asyncstageout/v1.0.4/sw.pre.dciangot/slc6_amd64_gcc481/external/p5-poe-component-child/1.39-comp/lib/perl5/POE/Component/Child.pm line 181
```

**Comment by HassenRiahi** [comment]
I think it is caused by the limit on the number of open files in the machine. We tuned that number in vocms031 in the past. Please have a look there and tune that number in vocms021.

**Comment by dciangot** [comment]
Yes, you are right. Done. Let's see if it is solved now and then lets close this.

**Comment by dciangot** [comment]
Ok, I confirm this is solved now.

**Comment by belforte** [comment]
shouldn't the limit on open files be set as part of the puppet install ? Or at worse of the ASO install. But certainly not something "we have to remember".

**Comment by dciangot** [comment]
I agree, just added a note in the wiki. I'm going to write down a section with all the stuff to remember to put a machine in production

**Comment by belforte** [comment]
who maintains the puppet profile for ASO nodes ?

**Comment by HassenRiahi** [comment]
maybe @juztas has the answer...reopening.

**Comment by juztas** [comment]
vocms021 ?

**Comment by HassenRiahi** [comment]
both

**Comment by juztas** [comment]
I do not see a crash on vocms031. vocms021 ask Diego to do one thing and will take a  look more after that.

**Comment by juztas** [comment]
did it myself. should be fixed

**Comment by juztas** [comment]
ech, was not reading the whole thread, and fixed one issue. So it was not only nofiles but also max processes allowed per user.

 puppet configs were in git.cern.ch and now they should be moved to gitlab.cern.ch You might want to confirm it with Ivan.

**Comment by HassenRiahi** [comment]
You can update this twiki: https://twiki.cern.ch/twiki/bin/view/CMSPublic/AsoDeployment that was maintained by Andres including the missed info.

**Comment by dciangot** [comment]
Still need to have it in puppet. I'm going to talk about it with @todor-ivanov

**Comment by dciangot** [comment]
This is done now. Closing.
