### ISSUE TITLE
Purge DB instead of the rotation

### ISSUE THREAD

**Issue by HassenRiahi** [dmwm/AsyncStageout#4491]
@geneguvo , the current prod. version of couch (1.6.1) comes with the purge API (http://docs.couchdb.org/en/1.6.1/api/database/misc.html). Does it make sense to give it a try? instead of the heavy DB rotation + views building that we are doing so far.

**Comment by belforte** [comment]
Hassen, can you be more clear ? rotation is not heavy now. Right ?
It is simply a switch to a new DB while the old one drains.
I do not think we want to test new API's in the production system,
but if you have time to try on a VM and get some performance numbers...

**Comment by HassenRiahi** [comment]
Stefano, we started to switch between DBs because the DB rotation was taking too long. We were doing the DB rotation to remove the reference to deleted documents from the DB in order to decrease its size. The rotation operation was done manually (copying the DB in a third machine, copy it back then from there and finally trigger the compaction of the views) and that is why it was taking too long. I am asking Diego if he is aware about this API which could save us from switching between DBs.

**Comment by dciangot** [comment]
Tested but without success. Abbandoned idea. Please close it.

@mmascher @belforte
