### ISSUE TITLE
GMT end and start time conflicting with Kibana monitor

### ISSUE THREAD

**Issue by dciangot** [dmwm/AsyncStageout#4496]
Right now the GMT is corrected by hand on kibana monitoring script, but it is not the optimal solution of course (e.g. it stopped working last Sunday due to summer time introduction). 

Shall we consider other solutions? The easiest way may be to fix the script in a smarter way.

Diego

**Comment by belforte** [comment]
what exactly is the problem ?
The most general solution to all those kind of problems is to use UTC everywhere. Since that is always well defined. Then one can always customize a specific presentation layer, of course making it clear in the presentation.

**Comment by dciangot** [comment]
Yes, correct. Moved to UTC and converted for Kibana presentation. Closing.
