### ISSUE TITLE
properly register username for USER dataset

### ISSUE THREAD

**Issue by belforte** [dmwm/AsyncStageout#4504]
see e.g.
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fphys03&input=dataset%3D%2Fnew_Spin0_pseudoscalar_m400_ToTTbar_LpJets%2Fmgul-GEN_SIM_new-7977369f2d646ccb9bf2cc10b9b17a61%2FUSER

when ASO publishes it puts local user name of who runs the code (dciangot) as dataset creator, it should be instead the user who ran the CRAB task (mgul)

```
DAS service: dbs3 DAS api: dataset_info
{
 "dataset": {
    "status": "VALID",
    "modified_by": "dciangot",
    "physics_group_name": "CRAB3",
    "acquisition_era_name": "CRAB",
    "prep_id": None,
    "processing_version": 1,
    "creation_time": "2016-05-16 12:01:26",
    "created_by": "dciangot",
    "processed_ds_name": "mgul-GEN_SIM_new-7977369f2d646ccb9bf2cc10b9b17a61",
    "modification_time": "2016-05-16 12:01:25",
    "datatype": "mc",
    "xtcrosssection": None,
    "dataset_id": 2292045,
    "primary_dataset": {
       "name": new_Spin0_pseudoscalar_m400_ToTTbar_LpJets
      },
    "data_tier_name": "USER",
    "name": /new_Spin0_pseudoscalar_m400_ToTTbar_LpJets/mgul-GEN_SIM_new-7977369f2d646ccb9bf2cc10b9b17a61/USER
   }
}

```

**Comment by dciangot** [comment]
I need to check better, but at first sight that may be due to a issue in retrieving the user proxy. 
Currently if the user proxy retrieving fails, the opsProxy is used to do the publication and that may lead to the dataset creator misconfiguration. So far it's just a guess, I'm still checking.

In case I was right, what do we want to do in case user proxy cannot be retrieved? Wait, fail or what?

**Comment by belforte** [comment]
It sounds like a very good theory. IIRC the username in DBS is not provided by the client but is the one CMSWEB maps the DN to (via SiteDB). If this is a rare situation, let's leave it aside for less busy times.

**Comment by belforte** [comment]
Let's keep it as it is, since it is very rare
