### ISSUE TITLE
Migrating ASO JobMonitor to FTS3 REST API

### ISSUE THREAD

**Issue by nikmagini** [dmwm/AsyncStageout#4513]
Dear CRAB3/ASO developers,

The FTS3 SOAP interfaces, together with the old glite-transfer-\* clients using them, will be retired by the end of the year.

Therefore, like PhEDEx, ASO will also need to migrate to use the FTS3 REST API
exclusively instead of the SOAP API before the end of the year.

Currently ASO is already using FTS3 REST for submission, but it's still using glite-transfer-status against FTS3 SOAP for transfer polling, with an implementation of the FTS JobMonitor copied from PhEDEx.

In PhEDEx we now have a new implementation of the FTS3 JobMonitor working with FTS3 REST and based on the new fts-transfer-\* clients (distributed with rpm fts-client-3.4.X or newer)

Looking at the ASO code, it should be relatively easy to update it to use the new PhEDEx code if you wish.

Just copy this file into ASO from PhEDEX with few minor modifications to fix the library imports:

https://github.com/dmwm/PHEDEX/blob/master/perl_lib/PHEDEX/Transfer/Backend/Interface/FTS3CLIAsync.pm

And update File.pm/Job.pm in ASO to support new FTS3 file/job states, see here for reference:

https://github.com/dmwm/PHEDEX/commit/5e3c69bbc65ef43d2b1c26d5d9e7013b9fbe190e

Please let us know your plans for this change.

Thanks!
Nicolò

**Comment by belforte** [comment]
Diego will work on this next week. See CRAB3 meeting minutes in
https://indico.cern.ch/event/574943/

**Comment by nikmagini** [comment]
Thanks Stefano! Please let me know if you need any help from my side on this.

**Comment by dciangot** [comment]
Following Nicolo' instructions I tested the changes on my vm first and then on preprod instance with few tasks. The PR is #4514.
Everything seems fine, but I may have overlooked some non-trivial cases. So if you have any comment or suggestion please let me know.
Diego

**Comment by dciangot** [comment]
It looks correctly working, we can close it IMO.

@belforte @mmascher

**Comment by belforte** [comment]
in production since a while
