### ISSUE TITLE
Enable FTS' checksum option.

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/AsyncStageout#4522]
I originally requested this at https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2599.html but realized it's probably better here.

Basically, it appears that CMS sites globally now support the fts3 checksumming (`-K`) option. Could we begin using it?

Cheers,
Andrew

**Comment by PerilousApricot** [comment]
Cheers, @belforte. Ideally it won't be a huge change, but it'll be nice to have that protection.

**Comment by dciangot** [comment]
It appears to be a long history (*). I would postpone the test of this feature (including being sure that really each site support it) after the ASO migration to Oracle is successfully completed.

(*) https://github.com/dmwm/AsyncStageout/issues/1871

**Comment by belforte** [comment]
@dciangot discussion in that issue is 4~5 years old. Surely a lot has changed. Let's ignore and handle as a new thing. @PerilousApricot says that PhEDEx uses it in production, which means every site supports it. So you can check with Transfer team etc. We do not really have a way to test it, we would simply make the change and cross fingers.

**Comment by dciangot** [comment]
Ok, sure, no problem for me then. I can push it up on priority and do it on next deployment (finger crossed).

**Comment by belforte** [comment]
You need to make sure first that we really understand what PhEDEx does and what we would be doing. No blind actions. And only do it if _YOU_ are convinced that it is good and workd.

**Comment by dciangot** [comment]
That was exactly was I said before. Since we are going to have a lot of changes soon and, envetually, unforseen new issues after the migration to Oracle, I would rather postpone it regardless the ease of the changes.

**Comment by dciangot** [comment]
I checked with Sebastian and looks like all the sites are ready to support this feature. [Here](https://cmsweb.cern.ch/phedex/prod/Components::Agents?pcolumn=TIME_UPDATE&pcolumn=NODE_NAME&pcolumn=FILENAME%3ARELEASE%3AREVISION%3ATAG) you can see that they are all running the PHEDEX_4_2_1 and then, in principle, using the FTS3 checksum (https://github.com/dmwm/PHEDEX/commit/1f4a07827eac3b6b28ca429c819300a502a3c49c).

So, I think we can fill confident enough to include it. It will be deployed in testbed on next round.

**Comment by PerilousApricot** [comment]
This is related to https://github.com/dmwm/CRABServer/issues/5319 as well
