### ISSUE TITLE
fix FTS3 monitoring link reported to dashboard

### ISSUE THREAD

**Issue by belforte** [dmwm/AsyncStageout#4523]
see
https://cern.service-now.com/service-portal/view-incident.do?n=INC1275344

**Comment by belforte** [comment]
looking at code, problem seems rather on dashboard side, will open a SNOW ticket

**Comment by belforte** [comment]
https://cern.service-now.com/service-portal/view-incident.do?n=INC1278405

**Comment by belforte** [comment]
let's keep this open, since it is not clear if we may not need to do something anyhow

**Comment by belforte** [comment]
Yes, it looks like we need to change on our side.

**Comment by belforte** [comment]
ideally we should change URL in the json file which is sent to AMQ in
https://github.com/dmwm/AsyncStageout/blob/master/src/python/AsyncStageOut/TransferWorker.py#L572
to be `https://fts3.cern.ch:8449/fts3/ftsmon/#/job/`
maybe as a first test, w/o messing with the worker, we can change the URL when we send the message to STOMP in
https://github.com/dmwm/AsyncStageout/blob/master/bin/DashboardNotifier.py#L16-L21
@dciangot what do you think ?

**Comment by dciangot** [comment]
I don't think that ideally we want hardcode that in ASO, since we can expect the url to change again in the future.  
For me it is way better the solution you proposed as the backup, and I agree to test it.

OTOH what was already in place is the ideal solution to me:
- ASO indicates the FTS server used
- the FTS server is mapped to a specific url for job status retrieving on collector side
but I understand that taking control of the second point may take some time.

**Comment by belforte** [comment]
Sounds goo. Shall I make a PR ?

**Comment by dciangot** [comment]
Fine for me.

**Comment by belforte** [comment]
this is not needed anymore, theres' a better fix on dashboard side which will work for other FTS servers than CERN as well
https://cern.service-now.com/service-portal/view-incident.do?n=INC1278405

**Comment by dciangot** [comment]
looks like broken again? https://dashb-cms-job-task.cern.ch/dashboard/request.py/ftsfilestatus?jobId=1702753488

I'm checking if it is just a particular case or not.

**Comment by dciangot** [comment]
OK, indeed I'm afraid is related to ASO/oracle bug in the dashboard report. 

@belforte can we reopen this and I'll take a look.

**Comment by dciangot** [comment]
https://github.com/dmwm/AsyncStageout/issues/4530
