### ISSUE TITLE
Fix dashboard report FTS url

### ISSUE THREAD

**Issue by dciangot** [dmwm/AsyncStageout#4530]
Dashboard report provides broken url to the dashboard in Oracle instance.

**Comment by belforte** [comment]
problem happened again on dashboard side. Opened SNOW
https://cern.service-now.com/service-portal/view-incident.do?n=INC1351700

**Comment by belforte** [comment]
the problem had initially fixed on dashboard side, see https://github.com/dmwm/AsyncStageout/issues/4523#issuecomment-278295772
If they can't make their fix stick, we'll have to change our URL

**Comment by belforte** [comment]
FIxed again in dashboard. Apparently ASO had added a trailing `/` to the reported URL which was confusing it
