### ISSUE TITLE
avoid publication failure due to lack of file metadata

### ISSUE THREAD

**Issue by belforte** [dmwm/AsyncStageout#4543]
looks like PostJob starts the transfer by uploading the file id with falg NEW in Oracle, but only upoads metadata later and at times the metadata upload happens very late. Maybe never ?

Diego increased wait for metadata from 5 to 30min before giving publication error, but at times this is not enouhg.

Waiting forever is not an option.

Diego and Stefano discussed and believe that best is that PostJob does not send transfer request unless metadata is in orable, so that whatever happens we are sure never pollute user store disk at T2 with files which will not be published. At that point ASO should simply fail when metadata is not there as it becomes a fatal error.

**Comment by belforte** [comment]
THis is mostly a matter of reviewing and changin CRAB SERVER PostJob, will open issue there as well

**Comment by mmascher** [comment]
Hi, this has always been like that. I am not sure how much was the timeout before, but to me having the "filemetadata upload" being the last thing the postjob does makes sense. It prevents things like ASO publishing but PJ failing between the upload and the end making status and publication states inconsistent.

**Comment by belforte** [comment]
I disagree.
Note that now transfers are only started by PostJob. There is no way for ASO to publish
until PostJob say so, simply PostJob will not say "do it" unless PostJob is sure that metadata are in Oracle.
If we need another state in ASO, so be it.
But we should not have : go ahead, I'll do something for you in the meanwhile but no promise.
Maybe we can chat about this ?

**Comment by mmascher** [comment]
It's true that now that we do not have the transfer started from the WN and we do not have to deal with condor restart it should be safer to "anticipate" the upload of the filemetadata. I am just trying to understand why this is suddenly a problem that needs to be addressed. It implies an architectural change and those are never easy in my experience (there is always something you do not think about)..

**Comment by belforte** [comment]
On 05/03/2017 05:12 PM, Marco Mascheroni wrote:
> I am just trying to understand why this is suddenly a problem that needs to be addresse

I think because now that ASO uses Oracle it is so fast that
it notices that a file is ready for publication before the
POstJob has got to upload the metadata, esp. if there's
some intermittent problem with CRABSERVER.
In a way, it does not matter which one is done first,
what matter is that ASO can tell that everything is OK.
We surely can send file info from WN and start xfer, if
that helps, the important things is that ASO waits for
a final GO from CrabServer before attempting publication.

THis could very well be a "misunderstanding" rather than a bug.
I.e. all needed signals are there, but ASO, PostJob, Diego,
Stefano and Marco do not all agree on what they mean !

**Comment by mmascher** [comment]
I think the question is: "do we want to attempt the publication of a file if its associated (post)job is not in the finished state?". If the answer is "No" then I'd like to keep things as they are and consider the filemetadata upload as the signal that the PJ has finished.

But I agree that it iss trange that we have these problems only lately with Oracle.

**Comment by belforte** [comment]
but then, wouldn't it be simpler to set the "to Publish" flag when metadata is uploaded ?

The problem now is that you say "consider metadata upload as the signal"
but ASO picks from the DB the list of files with "toPublish" and starts
publication process for those as soon as they are transferred.
Possible lack of metadata is currently handled like an exception, not as
a precondition. That's the problem. Why it was not clear before, does not matter.
Something has to change.

And of course.. nothing guarantees that PostJobs keeps running after it uploaded metadata, the only 
thing we can check is that ASO does not start until PJ has reached a certain step.
In the end, there are simply two process which communicate, we must write down the protocol.
As usual, it will all be more clear in front of that writeup.
