### ISSUE TITLE
Insert primary datasets that is already in DBS again and again

### ISSUE THREAD

**Issue by yuyiguo** [dmwm/AsyncStageout#4552]
There were hundreds of Oracle errors in DBS log that were similar to below:
WARNING:cherrypy.error:DBSPrimaryDataset/insertPrimaryDataset: Unique constraint violation being ignored...
WARNING:cherrypy.error:(IntegrityError) ORA-00001: unique constraint (CMS_DBS3_PROD_PHYS03_OWNER.TUC_PDS_PRIMARY_DS_NAME) violated
   ' insert into cms_dbs3_prod_phys03_owner.PRIMARY_DATASETS( PRIMARY_DS_NAME,CREATE_BY,PRIMARY_DS_TYPE_ID,CREATION_DATE,PRIMARY_DS_ID)  values(:primary_ds_name,:create_by,:primary_ds_type_id,:creation_date,:primary_ds_id )' {'create_by': 'dciangot', 'primary_ds_name': 'SingleMuon', 'primary_ds_id': 6476035, 'primary_ds_type_id': 2, 'creation_date': 1518463155.549403}

This error was caused by https://github.com/dmwm/AsyncStageout/blob/master/src/python/AsyncStageOutSure/PublisherWorker.py#L1231 that insert a primary dataset to DBS no mater if it is already in or not. Then the same primary dataset and a block of data was inserted in the same function using bulkblock API, as below:
https://github.com/dmwm/AsyncStageout/blob/master/src/python/AsyncStageOut/PublisherWorker.py#L1418

The Line 1418 that call bulkblock insert will take care the primary dataset insert anyway if it is not in DBS yet. So the line 1231 that explicitly insert the primary dataset can be removed.

**Comment by belforte** [comment]
@dciangot can do you do this ? Or do I have to ?

**Comment by belforte** [comment]
@dciangot ping
the code change is simple, the question is really how confident are we to build and deploy a new ASO version
